apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-cm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TobiasKohlerT/test.git #git@github.com:TobiasKohlerT/test.git
    path: config-map/cm.yaml
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false